[general]
dirs = ["templates"]
default_syntax = "silphium"

[[syntax]]
name = "silphium"
block_start = "<!--{%"
block_end = "%}-->"
comment_start = "<!--{#"
comment_end = "#}-->"
expr_start = "<!--{{"
expr_end = "}}-->"
