name: 'VirusTotal scan'
description: 'Uploads Rust binaries to VirusTotal for scanning'
inputs:
  vt_api_key:
    description: 'VirusTotal API key'
    required: true
  executable-name:
    description: 'Executable name'
    required: true
  target:
    description: 'Build target'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Find executable
      shell: bash
      run: |
        VT_EXECUTABLE=target/${{ inputs.target }}/release/${{ inputs.executable-name }}${{ inputs.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
        echo "VT_EXECUTABLE=$VT_EXECUTABLE" >> $GITHUB_ENV
    - name: Perform scan
      id: virus_total
      uses: crazy-max/ghaction-virustotal@d34968c958ae283fe976efed637081b9f9dcf74f
      with:
        vt_api_key: ${{ inputs.vt_api_key }}
        files: ${{ env.VT_EXECUTABLE }}
    - name: Parse analysis link
      shell: bash
      run: |
        VT_ANALYSIS=$(echo '${{ steps.virus_total.outputs.analysis }}' | cut -d = -f 2- -)
        echo "VT_ANALYSIS=$VT_ANALYSIS" >> $GITHUB_ENV
    - name: Add analysis link
      shell: bash
      run: |
        echo "# VirusTotal analysis" >> $GITHUB_STEP_SUMMARY
        echo "$VT_ANALYSIS" >> $GITHUB_STEP_SUMMARY
