name: 'Download artifact'
description: 'Downloads an artifact'
inputs:
  name:
    description: 'Artifact name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download artifact
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
      with:
        name: ${{ inputs.name }}
