name: 'Mount mod'
description: 'Mounts a mod folder for testing'
inputs:
  rclone-config:
    description: 'rclone configuration'
    required: true
  remote-name:
    description: 'Name of the rclone remote to use'
    required: true
  remote-path:
    description: 'Name of the remote path to mount'
    required: true
  mount-path:
    description: 'Path where to mount the remote'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@0d99fa3878a334d3e307c1a8372ad55550fdaea7
      with:
        rclone_config: ${{ inputs.rclone-config }}
    - name: Create mods folder
      shell: bash
      run: |
        mkdir -p ${{ inputs.mount-path }}
    - name: Mount mods folder
      shell: bash
      run: |
        rclone mount --daemon --read-only ${{ inputs.remote-name }}:${{ inputs.remote-path }} ${{ inputs.mount-path }}
