name: 'Deploy to GitHub Pages'
description: 'Deploys a static site to GitHub Pages'
inputs:
  path:
    description: 'Path to deploy'
    required: true
outputs:
  page-url:
    description: "GitHub Pages URL"
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: 'composite'
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b
    - name: Prepare Pages artifact
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
      with:
        path: ${{ input.path }}
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
