name: 'Run FAUST'
description: 'Runs FAUST'
inputs:
  faust:
    description: 'Path to FAUST executable'
    required: false
    default: 'faust'
  manifest:
    description: 'Path to FAUST manifest'
    required: true
  base:
    description: 'Path to FAUST manifest'
    required: true
  out-dir:
    description: 'Path to output'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build site
      shell: bash
      run: |
        ./${{ inputs.faust }} --verbose ${{ inputs.manifest }} --base-game-path ${{ inputs.base }} --out-dir ${{ inputs.out-dir }}
