name: Audit dependencies

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/audit.yml"
      - ".cargo/audit.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  security_audit:
    name: 'Dependency audit'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Run audit
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
