name: Security audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/audit.yml"
      - "audit.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  security_audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
