name: Build FAUST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build (Linux)
      run: cargo build --verbose
    - name: Build (Windows)
      uses: houseabsolute/actions-rust-cross@v1
      with:
        command: build
        target: x86_64-pc-windows-gnu
        args: "--locked --release"
    - name: Publish artifacts and release
      uses: houseabsolute/actions-rust-release@v0
      with:
        executable-name: faust
        target: x86_64-pc-windows-gnu
