name: Build releases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Build Linux release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --locked --verbose

  windows:
    name: Build Windows release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu --release --locked --verbose

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [windows, linux]
    steps:
    - name: Publish artifacts and release
      uses: houseabsolute/actions-rust-release@v0
      with:
        executable-name: faust
        target: x86_64-pc-windows-gnu
