name: Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-name: Windows
            runs-on: windows-2025
            target: x86_64-pc-windows-msvc
          - os-name: macOS
            runs-on: macOS-15
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
      - name: Virus scan
        uses: ./.github/actions/vt-scan/
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          executable-name: faust
          target: ${{ matrix.platform.target }}
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: faust
          target: ${{ matrix.platform.target }}
          archive-name: faust-${{ github.ref_name }}-${{ matrix.platform.os-name }}
