name: Test mod sites

on:
  push:
    branches:
      - main
  pull_request: # temporarily for testing the action

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build FAUST
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: x86_64-unknown-linux-gnu
          args: "--locked --release"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: faust
          path: target/x86_64-unknown-linux-gnu/release/faust
  test:
    name: Test - ${{ matrix.mod.name }}
    needs: build
    runs-on: ubuntu-24.04
    environment: preview
    permissions:
      contents: read
      deployments: write
    strategy:
      fail-fast: false
      matrix:
        mod:
          - id: og
            name: "[OG] Imperial Campaign"
            dir: og
            base: og
          - id: og-bi
            name: "[OG] Barbarian Invasion"
            dir: og-bi
            base: og
          - id: og-alx
            name: "[OG] Alexander"
            dir: og-alx
            base: og
          - id: og-be-hl
            name: "[OG] Hellenistic Legacy"
            dir: og-be-hl
            base: og
          - id: og-xc5
            name: "[OG] Extended Cultures V"
            dir: og-xc5
            base: og
          - id: og-fatw
            name: "[OG] Fourth Age"
            dir: og-fatw
            base: og
          - id: og-eod
            name: "[OG] End of Days"
            dir: og-eod
            base: og
          - id: og-dtw
            name: "[OG] Diadochi"
            dir: og-dtw
            base: og
          - id: og-vtw
            name: "[OG] Viking"
            dir: og-vtw
            base: og
          # - id: og-ibrr
          #   name: "[OG] Invasio Barbarorum"
          #   dir: og-ibrr
          #   base: og
          - id: og-aristeia
            name: "[OG] Aristeia"
            dir: og-aristeia
            base: og
          - id: rr
            name: "[RR] Imperial Campaign"
            dir: rr
            base: rr
          - id: rr-bi
            name: "[RR] Barbarian Invasion"
            dir: rr-bi
            base: rr
          - id: rr-alx
            name: "[RR] Alexander"
            dir: rr-alx
            base: rr
          - id: rr-lotr
            name: "[RR] The Lord of the Rings"
            dir: rr-lotr
            base: rr
          - id: rr-chivalry
            name: "[RR] Chivalry"
            dir: rr-chivalry
            base: rr
          - id: rr-haw
            name: "[RR] Hellenism at War"
            dir: rr-haw
            base: rr
          - id: rr-tc
            name: "[RR] Total Conquest"
            dir: rr-tc
            base: rr
          - id: rr-ris
            name: "[RR] RTR Imperium Surrectum"
            dir: rr-ris
            base: rr
          - id: rr-eb1
            name: "[RR] Europa Barbarorum"
            dir: rr-eb1
            base: rr
          - id: rr-gor
            name: "[RR] Glory of Rome"
            dir: rr-gor
            base: rr
          - id: rr-cc
            name: "[RR] Cultural Conquest"
            dir: rr-cc
            base: rr
          - id: rr-toa
            name: "[RR] Tales of Antiquity"
            dir: rr-toa
            base: rr
          - id: rr-be
            name: "[RR] Barbarian Empires"
            dir: rr-be
            base: rr
          - id: m2
            name: "[M2] Grand Campaign"
            dir: m2
            base: m2
          # - id: m2-americas
          #   name: "[M2] Americas"
          #   dir: m2-americas
          #   base: m2
          # - id: m2-britannia
          #   name: "[M2] Britannia"
          #   dir: m2-britannia
          #   base: m2
          # - id: m2-crusades
          #   name: "[M2] Crusades"
          #   dir: m2-crusades
          #   base: m2
          # - id: m2-teutonic
          #   name: "[M2] Teutonic"
          #   dir: m2-teutonic
          #   base: m2
          - id: m2-id
            name: "[M2] Insularis Draco"
            dir: m2-id
            base: m2
          - id: m2-roq
            name: "[M2] Rise of Quetzal"
            dir: m2-roq
            base: m2
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Mount mods folder
        shell: bash
        run: |
          mkdir -p mods
          rclone mount --daemon --read-only faust:faust-data mods
      - name: Download FAUST
        uses: actions/download-artifact@v4
        with:
          name: faust
      - name: Build site
        shell: bash
        run: |
          chmod +x faust
          ./faust --verbose mods/${{ matrix.mod.dir }}/faust/faust.yml --base-game-path mods/${{ matrix.mod.base }} --out-dir output/
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy output/ --project-name=silphium --branch=${{ github.event_name == 'pull_request' && format('{0}/', github.ref_name) || '' }}${{ matrix.mod.id }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
