name: Test mod sites

on:
  push:
    branches:
      - main
  pull_request: # temporarily for testing the action

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build FAUST
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Build binary
        uses: ./.github/actions/rust-build/
        with:
          target: x86_64-unknown-linux-gnu
      - name: Upload binary
        uses: ./.github/actions/artifact/upload/
        with:
          name: faust
          path: target/x86_64-unknown-linux-gnu/release/faust

  test:
    name: Test - ${{ matrix.mod.name }}
    needs: build
    runs-on: ubuntu-24.04
    environment: preview-${{ matrix.mod.id }}
    permissions:
      contents: read
      deployments: write
    strategy:
      fail-fast: false
      matrix:
        mod:
          - id: og
            name: '[OG] Imperial Campaign'
            dir: og
            base: og
          - id: og-bi
            name: '[OG] Barbarian Invasion'
            dir: og-bi
            base: og
          - id: og-alx
            name: '[OG] Alexander'
            dir: og-alx
            base: og
          - id: og-be-hl
            name: '[OG] Hellenistic Legacy'
            dir: og-be-hl
            base: og
          - id: og-xc5
            name: '[OG] Extended Cultures V'
            dir: og-xc5
            base: og
          - id: og-fatw
            name: '[OG] Fourth Age'
            dir: og-fatw
            base: og
          - id: og-eod
            name: '[OG] End of Days'
            dir: og-eod
            base: og
          - id: og-dtw
            name: '[OG] Diadochi'
            dir: og-dtw
            base: og
          - id: og-vtw
            name: '[OG] Viking'
            dir: og-vtw
            base: og
          - id: og-aristeia
            name: '[OG] Aristeia'
            dir: og-aristeia
            base: og
          - id: rr
            name: '[RR] Imperial Campaign'
            dir: rr
            base: rr
          - id: rr-bi
            name: '[RR] Barbarian Invasion'
            dir: rr-bi
            base: rr
          - id: rr-alx
            name: '[RR] Alexander'
            dir: rr-alx
            base: rr
          - id: rr-lotr
            name: '[RR] The Lord of the Rings'
            dir: rr-lotr
            base: rr
          - id: rr-chivalry
            name: '[RR] Chivalry'
            dir: rr-chivalry
            base: rr
          - id: rr-haw
            name: '[RR] Hellenism at War'
            dir: rr-haw
            base: rr
          - id: rr-arthur
            name: '[RR] Arthurian: Total War'
            dir: rr-arthur
            base: rr
          - id: rr-tc
            name: '[RR] Total Conquest'
            dir: rr-tc
            base: rr
          # - id: rr-ris
          #   name: '[RR] RTR Imperium Surrectum'
          #   dir: rr-ris
          #   base: rr
          - id: rr-eb1
            name: '[RR] Europa Barbarorum'
            dir: rr-eb1
            base: rr
          - id: rr-gor
            name: '[RR] Glory of Rome'
            dir: rr-gor
            base: rr
          - id: rr-cc
            name: '[RR] Cultural Conquest'
            dir: rr-cc
            base: rr
          - id: rr-toa
            name: '[RR] Tales of Antiquity'
            dir: rr-toa
            base: rr
          - id: rr-be
            name: '[RR] Barbarian Empires'
            dir: rr-be
            base: rr
          - id: rr-batw
            name: '[RR] Bronze Age'
            dir: rr-batw
            base: rr
          - id: rr-diadochi
            name: '[RR] Diadochi'
            dir: rr-diadochi
            base: rr
          - id: rr-fatw
            name: '[RR] Fourth Age'
            dir: rr-fatw
            base: rr
          - id: rr-malazan
            name: '[RR] Malazan'
            dir: rr-malazan
            base: rr
          - id: rr-rop
            name: '[RR] Rise of Persia'
            dir: rr-rop
            base: rr
          - id: rr-sg
            name: '[RR] Scorched Ground'
            dir: rr-sg
            base: rr
          - id: rr-tetrarchy
            name: '[RR] Tetrarchy'
            dir: rr-tetrarchy
            base: rr
          - id: m2
            name: '[M2] Grand Campaign'
            dir: m2
            base: m2
          - id: m2-americas
            name: '[M2] Americas'
            dir: m2-americas
            base: m2
          - id: m2-britannia
            name: '[M2] Britannia'
            dir: m2-britannia
            base: m2
          - id: m2-crusades
            name: '[M2] Crusades'
            dir: m2-crusades
            base: m2
          - id: m2-teutonic
            name: '[M2] Teutonic'
            dir: m2-teutonic
            base: m2
          - id: m2-id
            name: '[M2] Insularis Draco'
            dir: m2-id
            base: m2
          - id: m2-roq
            name: '[M2] Rise of Quetzal'
            dir: m2-roq
            base: m2
          - id: m2-bcki
            name: '[M2] Broken Crescent'
            dir: m2-bcki
            base: m2
          - id: m2-kgcm
            name: '[M2] Kingdoms Grand Campaign'
            dir: m2-kgcm
            base: m2
          - id: m2-jlmpvk
            name: '[M2] Vanilla Kingdoms'
            dir: m2-jlmpvk
            base: m2
          - id: m2-timur
            name: '[M2] Timur: Total War'
            dir: m2-timur
            base: m2
          - id: m2-tgc
            name: '[M2] The Great Conflicts'
            dir: m2-tgc
            base: m2
          - id: m2-ebii
            name: '[M2] Europa Barbarorum II'
            dir: m2-ebii
            base: m2
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Download FAUST
        uses: ./.github/actions/artifact/download-executable/
        with:
          name: faust
      - name: Download test data
        uses: ./.github/actions/download-mod-data/
        with:
          mod-id: ${{ matrix.mod.id }}
      - name: Build site
        uses: ./.github/actions/faust/
        with:
          manifest: ${{ matrix.mod.dir }}/faust/faust.yml
          base: ${{ matrix.mod.base }}
          out-dir: output/
      - name: Deploy
        uses: ./.github/actions/cf-pages/
        with:
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHub-token: ${{ secrets.GITHUB_TOKEN }}
          path: output/
          project: silphium
          branch: ${{ github.event_name == 'pull_request' && format('{0}/', github.ref_name) || '' }}${{ matrix.mod.id }}
